<a href="https://colab.research.google.com/github/ArganaAdrian/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##Problem 1
```




In [7]:
import numpy as np
A = np.array([[1, 1, 1],[1, 0, 4],[0, 0, 5]])
print(f'Matrix A:\n {A}')
print()
B = np.array([[89],[89],[95]])
print(f'Matrix B:\n {A}')
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix A:\n{C}')

Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:
[[13.]
 [57.]
 [19.]]


##Problem 2

##Problem 3

In [5]:
import numpy as np
from numpy.linalg import eig

A = np.array([[8,5,6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A)

print("The Eigenvalues are: \n",w)
print("The Eigenvectors are: \n",v.round())

[[  8   5   6]
 [-12  -9  12]
 [ -3  -3   5]] 

The Eigenvalues are: 
 [0.5+5.80947502j 0.5-5.80947502j 3. +0.j        ]
The Eigenvectors are: 
 [[-0.-0.j -0.+0.j  1.+0.j]
 [ 1.+0.j  1.-0.j -1.+0.j]
 [ 0.+0.j  0.-0.j  0.+0.j]]
