<a href="https://colab.research.google.com/github/ArganaAdrian/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
 #Answer for 1 A
W = np.array([[1,-3],[2,-2],[3,1]])
Y = np.array ([[1,2,0],[0,-1,-2]])
print(np.dot(W,Y))

[[ 1  5  6]
 [ 2  6  4]
 [ 3  5 -2]]


In [29]:
#Answer for 1 B
Z = np.array([[0,1],[2,3]])
Z = np.array([[0,1],[2,3]])
print (Z+Z)

[[0 2]
 [4 6]]


In [30]:
#Answer for 1 C
X = np.array([[3,2,1],[-1,2,3],[2,-1,-1]])
print (3*X)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3 -3]]


In [31]:
#Answer for 2 A
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
print(np.dot(Y,W)^2)

[[ 7 -5]
 [ 6  6]]


In [32]:
#Answer for 2 B
R = np.dot(W,Y)
R

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

In [33]:
#Answer for 2 B
print(np.subtract(R,X))

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  3]]


In [34]:
#Answer for 2 C
Y = np.array([[1,2,0],[0,-1,2]])
W = np.array([[1,-3],[2,-2],[3,1]])
Z = np.array([[0,1],[2,3]])
print(np.dot(Y,W)-Z^2)

[[ 7 -6]
 [ 0  3]]
