<a href="https://colab.research.google.com/github/ArganaAdrian/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QUESTION 1

In [10]:
import numpy as np
C = np.zeros((4,4)) #this where the 4 x 4 matrix
np.fill_diagonal(c, 1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# QUESTION 2

In [6]:
import numpy as np
c = np.zeros((4,4)) #this where the 4 x 4 matrix
np.fill_diagonal(c,1) 

print("c= ")
print(c)

print("Doubled:")
print(2*c)

c= 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Doubled:
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


# QUESTION 3

In [1]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])

cross = np.cross(A,B)
print(cross)

[20 -4 -3]
