<a href="https://colab.research.google.com/github/ArganaAdrian/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#sum = A + B
import numpy as np
A = np.array(([-5,0],[4,1]))
B = np.array(([6,-3],[2,3]))
print (A+B)

[[ 1 -3]
 [ 6  4]]


In [8]:
#difference1 = A - B
A = np.array(([-5,0],[4,1]))
B = np.array(([6,-3],[2,3]))
print (A-B)

[[-11   3]
 [  2  -2]]


In [9]:
#difference2 = B - B
B=np.array(([6,-3],[2,3]))
B=np.array(([6,-3],[2,3]))
print (B-B)

[[0 0]
 [0 0]]
