<a href="https://colab.research.google.com/github/ArganaAdrian/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vector Spaces and Its Operations**




In [1]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [2]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape

(2, 3)

In [3]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
print(pool.shape)
print(pool.size)

(2, 3)
6


In [4]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape
pool.ndim

2

In [5]:
U = np.array ([[1,2,3,],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
U = np.array ([[1,2,3,],[4,5,6]])
U.shape

(2, 3)

In [7]:
U = np.array ([[1,2,3,],[4,5,6]])
U.ndim

2

In [8]:
U = np.array ([[1,2,3,],[4,5,6]])
U.size

6

In [9]:
U = np.array ([[1,2,3,],[4,5,6]])
U
U.size

6

# **Addition of Vectors**

In [10]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [11]:
R = np.add(A,B)
R

array([ 6, -2])

In [12]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [13]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = addend1 + addend2
resultant

array([1, 1, 0])

# **Subtraction of Vector**

In [14]:
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [15]:
R = np.subtract(A,B)
R

array([2, 8])

In [16]:
#You will substract the components of addend2 from addend1 : addentd - addend2
difference = addend1 - addend2
difference

array([-1, -1,  0])

In [17]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

# **Scaling**

In [18]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

In [19]:
A = np.array([1,5,8,9])
S = np.multiply(5,A)
S

array([ 5, 25, 40, 45])

# **Vector Cross Product**

In [20]:
import numpy as np
#initialize arrays

A = np.array([2,3])
B = np.array([1,7])
#Compute the cross product
#(2x7),(3,1) = (14-3) = 11
output = np.cross(A,B)
print(output)

11


In [21]:
A = np.array([2,3])
B = np.array([1,7])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

11


In [22]:
A = np.array([2,3,4])
B = np.array([1,7,0])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

[-28   4  11]


In [23]:
output = np.dot(A,B) #comput the dot product
print(output) #(2x1) = 2 (3x7)= 21 (4x0)= 0

23


In [24]:
A = np.array([2,7])
B = np.array([1,7])

output = np.cross(A,B)
print(output)

7


In [25]:
output = np.dot(A,B) #compute the dot product
print(output)

51


In [26]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

#Compute the dot product of A and B
dot = np.dot(A,B)
print(dot)

23
